openapi: 3.0.3

info:
  title: severless-offline-sqlite
  description: REST形式のサンプルAPI
  version: 1.0.0
  contact:
    name: Kosuke Sugimoto
    email: xxx@xxx.com

servers:
  - url: 'http://localhost:3000'
    description: ローカル開発環境

paths:
  /users:
    post:
      summary: データベースに新しいデータを追加
      operationId: RegisterSingleUser
      requestBody:
        $ref: '#/components/requestBodies/default'
      responses:
        '200':
          $ref: '#/components/responses/status_200'
        '404':
          $ref: '#/components/responses/status_404'
    get:
      summary: データベースにある全てのデータを取得
      operationId: FetchAllUser
      responses:
        '200':
          $ref: '#/components/responses/status_200'
        '404':
          $ref: '#/components/responses/status_404'
  /users/{user_id}:
    get:
      summary: 指定されたidのデータを取得
      operationId: FetchSingleUser
      parameters:
        - $ref: '#/components/parameters/default'
      responses:
        '200':
          $ref: '#/components/responses/status_200'
        '404':
          $ref: '#/components/responses/status_404'
    put:
      summary: 指定されたユーザーIDのデータを更新
      operationId: UpdateSingleUser
      parameters:
        - $ref: '#/components/parameters/default'
      requestBody:
        $ref: '#/components/requestBodies/default'
      responses:
        '200':
          $ref: '#/components/responses/status_200'
        '404':
          $ref: '#/components/responses/status_404'
    delete:
      summary: 指定されたユーザーIDのデータを削除
      operationId: DeleteSingleUser
      parameters:
        - $ref: '#/components/parameters/default'
      responses:
        '200':
          $ref: '#/components/responses/status_200'
        '404':
          $ref: '#/components/responses/status_404'

components:
  requestBodies:
    default:
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - age
            properties:
              name:
                type: string
              age:
                type: integer
  parameters:
    default:
      name: user_id
      in: path
      required: true
      schema:
        type: string
      description: ユーザーID
  responses:
    status_200:
      description: 成功時
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
              body:
                type: object
    status_404:
      description: データ未発見時
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: integer
              body:
                type: string
